// Code generated by MockGen. DO NOT EDIT.
// Source: payment_attempt.go
//
// Generated by this command:
//
//	mockgen -source=payment_attempt.go -destination=mocks/mock_payment_attempt.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentAttemptRepositoryInterface is a mock of PaymentAttemptRepositoryInterface interface.
type MockPaymentAttemptRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAttemptRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockPaymentAttemptRepositoryInterfaceMockRecorder is the mock recorder for MockPaymentAttemptRepositoryInterface.
type MockPaymentAttemptRepositoryInterfaceMockRecorder struct {
	mock *MockPaymentAttemptRepositoryInterface
}

// NewMockPaymentAttemptRepositoryInterface creates a new mock instance.
func NewMockPaymentAttemptRepositoryInterface(ctrl *gomock.Controller) *MockPaymentAttemptRepositoryInterface {
	mock := &MockPaymentAttemptRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentAttemptRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAttemptRepositoryInterface) EXPECT() *MockPaymentAttemptRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentAttemptRepositoryInterface) Create(ctx context.Context, request domain.PaymentAttempt) (domain.PaymentAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.PaymentAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentAttemptRepositoryInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentAttemptRepositoryInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockPaymentAttemptRepositoryInterface) Update(ctx context.Context, request domain.PaymentAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentAttemptRepositoryInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentAttemptRepositoryInterface)(nil).Update), ctx, request)
}
