// Code generated by MockGen. DO NOT EDIT.
// Source: trial_class.go
//
// Generated by this command:
//
//	mockgen -source=trial_class.go -destination=mocks/mock_trial_class.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTrialClassRepositoryInterface is a mock of TrialClassRepositoryInterface interface.
type MockTrialClassRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrialClassRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTrialClassRepositoryInterfaceMockRecorder is the mock recorder for MockTrialClassRepositoryInterface.
type MockTrialClassRepositoryInterfaceMockRecorder struct {
	mock *MockTrialClassRepositoryInterface
}

// NewMockTrialClassRepositoryInterface creates a new mock instance.
func NewMockTrialClassRepositoryInterface(ctrl *gomock.Controller) *MockTrialClassRepositoryInterface {
	mock := &MockTrialClassRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTrialClassRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrialClassRepositoryInterface) EXPECT() *MockTrialClassRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTrialClassRepositoryInterface) Create(ctx context.Context, request domain.TrialClass) (domain.TrialClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.TrialClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTrialClassRepositoryInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrialClassRepositoryInterface)(nil).Create), ctx, request)
}

// InsertMember mocks base method.
func (m *MockTrialClassRepositoryInterface) InsertMember(ctx context.Context, request domain.TrialClassMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMember", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMember indicates an expected call of InsertMember.
func (mr *MockTrialClassRepositoryInterfaceMockRecorder) InsertMember(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMember", reflect.TypeOf((*MockTrialClassRepositoryInterface)(nil).InsertMember), ctx, request)
}

// Update mocks base method.
func (m *MockTrialClassRepositoryInterface) Update(ctx context.Context, request domain.TrialClass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTrialClassRepositoryInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTrialClassRepositoryInterface)(nil).Update), ctx, request)
}
