// Code generated by MockGen. DO NOT EDIT.
// Source: booking.go
//
// Generated by this command:
//
//	mockgen -source=booking.go -destination=mocks/mock_booking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepositoryInterface is a mock of BookingRepositoryInterface interface.
type MockBookingRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryInterfaceMockRecorder is the mock recorder for MockBookingRepositoryInterface.
type MockBookingRepositoryInterfaceMockRecorder struct {
	mock *MockBookingRepositoryInterface
}

// NewMockBookingRepositoryInterface creates a new mock instance.
func NewMockBookingRepositoryInterface(ctrl *gomock.Controller) *MockBookingRepositoryInterface {
	mock := &MockBookingRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepositoryInterface) EXPECT() *MockBookingRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBookingRepositoryInterface) Create(ctx context.Context, request domain.Booking) (domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockBookingRepositoryInterface) Update(ctx context.Context, request domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBookingRepositoryInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookingRepositoryInterface)(nil).Update), ctx, request)
}
