// Code generated by MockGen. DO NOT EDIT.
// Source: parent.go
//
// Generated by this command:
//
//	mockgen -source=parent.go -destination=mocks/mock_parent.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockParentRepositoryInterface is a mock of ParentRepositoryInterface interface.
type MockParentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockParentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockParentRepositoryInterfaceMockRecorder is the mock recorder for MockParentRepositoryInterface.
type MockParentRepositoryInterfaceMockRecorder struct {
	mock *MockParentRepositoryInterface
}

// NewMockParentRepositoryInterface creates a new mock instance.
func NewMockParentRepositoryInterface(ctrl *gomock.Controller) *MockParentRepositoryInterface {
	mock := &MockParentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockParentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParentRepositoryInterface) EXPECT() *MockParentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParentRepositoryInterface) Create(ctx context.Context, request domain.Parent) (domain.Parent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Parent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockParentRepositoryInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParentRepositoryInterface)(nil).Create), ctx, request)
}

// GetByID mocks base method.
func (m *MockParentRepositoryInterface) GetByID(ctx context.Context, request int64) (domain.Parent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, request)
	ret0, _ := ret[0].(domain.Parent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockParentRepositoryInterfaceMockRecorder) GetByID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockParentRepositoryInterface)(nil).GetByID), ctx, request)
}
