// Code generated by MockGen. DO NOT EDIT.
// Source: student.go
//
// Generated by this command:
//
//	mockgen -source=student.go -destination=mocks/mock_student.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentRepositoryInterface is a mock of StudentRepositoryInterface interface.
type MockStudentRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockStudentRepositoryInterfaceMockRecorder is the mock recorder for MockStudentRepositoryInterface.
type MockStudentRepositoryInterfaceMockRecorder struct {
	mock *MockStudentRepositoryInterface
}

// NewMockStudentRepositoryInterface creates a new mock instance.
func NewMockStudentRepositoryInterface(ctrl *gomock.Controller) *MockStudentRepositoryInterface {
	mock := &MockStudentRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockStudentRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepositoryInterface) EXPECT() *MockStudentRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStudentRepositoryInterface) Create(ctx context.Context, request domain.Student) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStudentRepositoryInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentRepositoryInterface)(nil).Create), ctx, request)
}

// GetByID mocks base method.
func (m *MockStudentRepositoryInterface) GetByID(ctx context.Context, request int64) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, request)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudentRepositoryInterfaceMockRecorder) GetByID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudentRepositoryInterface)(nil).GetByID), ctx, request)
}
