// Code generated by MockGen. DO NOT EDIT.
// Source: trial_class.go
//
// Generated by this command:
//
//	mockgen -source=trial_class.go -destination=mocks/mock_trial_class.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTrialClassServiceInterface is a mock of TrialClassServiceInterface interface.
type MockTrialClassServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTrialClassServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTrialClassServiceInterfaceMockRecorder is the mock recorder for MockTrialClassServiceInterface.
type MockTrialClassServiceInterfaceMockRecorder struct {
	mock *MockTrialClassServiceInterface
}

// NewMockTrialClassServiceInterface creates a new mock instance.
func NewMockTrialClassServiceInterface(ctrl *gomock.Controller) *MockTrialClassServiceInterface {
	mock := &MockTrialClassServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTrialClassServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrialClassServiceInterface) EXPECT() *MockTrialClassServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTrialClassServiceInterface) Create(ctx context.Context, request domain.TrialClass) (domain.TrialClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.TrialClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTrialClassServiceInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrialClassServiceInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockTrialClassServiceInterface) Update(ctx context.Context, request domain.TrialClass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTrialClassServiceInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTrialClassServiceInterface)(nil).Update), ctx, request)
}
