// Code generated by MockGen. DO NOT EDIT.
// Source: parent.go
//
// Generated by this command:
//
//	mockgen -source=parent.go -destination=mocks/mock_parent.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockParentServiceInterface is a mock of ParentServiceInterface interface.
type MockParentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockParentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockParentServiceInterfaceMockRecorder is the mock recorder for MockParentServiceInterface.
type MockParentServiceInterfaceMockRecorder struct {
	mock *MockParentServiceInterface
}

// NewMockParentServiceInterface creates a new mock instance.
func NewMockParentServiceInterface(ctrl *gomock.Controller) *MockParentServiceInterface {
	mock := &MockParentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockParentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParentServiceInterface) EXPECT() *MockParentServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParentServiceInterface) Create(ctx context.Context, request domain.Parent) (domain.Parent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Parent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockParentServiceInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParentServiceInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockParentServiceInterface) Update(ctx context.Context, request domain.Parent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockParentServiceInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockParentServiceInterface)(nil).Update), ctx, request)
}
