// Code generated by MockGen. DO NOT EDIT.
// Source: payment_attempt.go
//
// Generated by this command:
//
//	mockgen -source=payment_attempt.go -destination=mocks/mock_payment_attempt.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentAttemptServiceInterface is a mock of PaymentAttemptServiceInterface interface.
type MockPaymentAttemptServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAttemptServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPaymentAttemptServiceInterfaceMockRecorder is the mock recorder for MockPaymentAttemptServiceInterface.
type MockPaymentAttemptServiceInterfaceMockRecorder struct {
	mock *MockPaymentAttemptServiceInterface
}

// NewMockPaymentAttemptServiceInterface creates a new mock instance.
func NewMockPaymentAttemptServiceInterface(ctrl *gomock.Controller) *MockPaymentAttemptServiceInterface {
	mock := &MockPaymentAttemptServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentAttemptServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAttemptServiceInterface) EXPECT() *MockPaymentAttemptServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentAttemptServiceInterface) Create(ctx context.Context, request domain.PaymentAttempt) (domain.PaymentAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.PaymentAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentAttemptServiceInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentAttemptServiceInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockPaymentAttemptServiceInterface) Update(ctx context.Context, request domain.PaymentAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentAttemptServiceInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentAttemptServiceInterface)(nil).Update), ctx, request)
}
