// Code generated by MockGen. DO NOT EDIT.
// Source: parent.go
//
// Generated by this command:
//
//	mockgen -source=parent.go -destination=mocks/mock_parent.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockParentServiceInterface is a mock of ParentServiceInterface interface.
type MockParentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockParentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockParentServiceInterfaceMockRecorder is the mock recorder for MockParentServiceInterface.
type MockParentServiceInterfaceMockRecorder struct {
	mock *MockParentServiceInterface
}

// NewMockParentServiceInterface creates a new mock instance.
func NewMockParentServiceInterface(ctrl *gomock.Controller) *MockParentServiceInterface {
	mock := &MockParentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockParentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParentServiceInterface) EXPECT() *MockParentServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParentServiceInterface) Create(ctx context.Context, request domain.Parent) (domain.Parent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Parent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockParentServiceInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParentServiceInterface)(nil).Create), ctx, request)
}

// GetByID mocks base method.
func (m *MockParentServiceInterface) GetByID(ctx context.Context, id int64) (domain.Parent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Parent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockParentServiceInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockParentServiceInterface)(nil).GetByID), ctx, id)
}
