// Code generated by MockGen. DO NOT EDIT.
// Source: student.go
//
// Generated by this command:
//
//	mockgen -source=student.go -destination=mocks/mock_student.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentServiceInterface is a mock of StudentServiceInterface interface.
type MockStudentServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStudentServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockStudentServiceInterfaceMockRecorder is the mock recorder for MockStudentServiceInterface.
type MockStudentServiceInterfaceMockRecorder struct {
	mock *MockStudentServiceInterface
}

// NewMockStudentServiceInterface creates a new mock instance.
func NewMockStudentServiceInterface(ctrl *gomock.Controller) *MockStudentServiceInterface {
	mock := &MockStudentServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStudentServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentServiceInterface) EXPECT() *MockStudentServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStudentServiceInterface) Create(ctx context.Context, request domain.Student) (domain.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request)
	ret0, _ := ret[0].(domain.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStudentServiceInterfaceMockRecorder) Create(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentServiceInterface)(nil).Create), ctx, request)
}

// Update mocks base method.
func (m *MockStudentServiceInterface) Update(ctx context.Context, request domain.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentServiceInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentServiceInterface)(nil).Update), ctx, request)
}
