// Code generated by MockGen. DO NOT EDIT.
// Source: booking.go
//
// Generated by this command:
//
//	mockgen -source=booking.go -destination=mocks/mock_booking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/soerjadi/booking/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingServiceInterface is a mock of BookingServiceInterface interface.
type MockBookingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockBookingServiceInterfaceMockRecorder is the mock recorder for MockBookingServiceInterface.
type MockBookingServiceInterfaceMockRecorder struct {
	mock *MockBookingServiceInterface
}

// NewMockBookingServiceInterface creates a new mock instance.
func NewMockBookingServiceInterface(ctrl *gomock.Controller) *MockBookingServiceInterface {
	mock := &MockBookingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBookingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingServiceInterface) EXPECT() *MockBookingServiceInterfaceMockRecorder {
	return m.recorder
}

// BookClass mocks base method.
func (m *MockBookingServiceInterface) BookClass(ctx context.Context, request domain.BookCLassRequest) (domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookClass", ctx, request)
	ret0, _ := ret[0].(domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookClass indicates an expected call of BookClass.
func (mr *MockBookingServiceInterfaceMockRecorder) BookClass(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookClass", reflect.TypeOf((*MockBookingServiceInterface)(nil).BookClass), ctx, request)
}

// Update mocks base method.
func (m *MockBookingServiceInterface) Update(ctx context.Context, request domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBookingServiceInterfaceMockRecorder) Update(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBookingServiceInterface)(nil).Update), ctx, request)
}
